version: 1
groups:
    - annotation: yukon configuration
      options:

          - key: ckanext.yukon.login.safe_ip
            editable: true
            type: list
            default: "127.0.0.1"
            description: |
                List of IPs that are allowed to login through native CKAN login
                form. `*` can be used as a wildcard, i.e: ``127.0.*.*``.

          - key: ckanext.yukon.login.ip_header
            editable: true
            default: X-Forwarded-For
            description: |
                Header that containing the real IP of the visitor. Set by
                reverse-proxy.

          - key: ckanext.yukon.limits.featured_datasets
            editable: true
            default: 3
            type: int
            description: |
              Number of featured datasets to show on the home page.

          - key: ckanext.yukon.limits.updated_information
            editable: true
            default: 3
            type: int
            description: |
              Number of information records shown on the home page.

          - key: ckanext.yukon.limits.added_request
            editable: true
            default: 3
            type: int
            description: |
              Number of requests shown on the home page.

          - key: ckanext.yukon.matomo.site_id
            default: "1"
            editable: true
            description: Matomo site ID for tracking

          - key: ckanext.yukon.matomo.tracker_url
            default: "https://analytics.gov.yk.ca/"
            editable: true
            description: Matomo tracking URL
