[app:main]
use = config:default.ini

###############################################################################
#                         Environment settings: start                         #
###############################################################################

## Database Settings
sqlalchemy.url = postgresql://ckan_default:pass@localhost/ckan_yukon
ckan.datastore.write_url = postgresql://ckan_default:pass@localhost/datastore_default
ckan.datastore.read_url = postgresql://datastore_default:pass@localhost/datastore_default

## Site Settings
ckan.site_url = http://yukon.ckan.local:5000

## Search Settings
solr_url = http://127.0.0.1:8983/solr/ckan_yukon

## ckanext-xloader
# ckanext.xloader.api_token = %(CKAN_XLOADER_API_TOKEN)s

## ckaneext-googleanalytics
# googleanalytics.id = G-TEST

# ckan.matomo_siteid = # 8 for production, 36 for UAT
# Matomo usage-data sync settings
ckanext.yukon.matomo.site_id = 1
ckanext.yukon.matomo.api_url = http://matomo.localhost
ckanext.yukon.matomo.token_auth = <matomo-api-token>

# Download-all settings
ckanext.downloadall.max_resource_size = 104857600
ckanext.downloadall.include_external_resources = false

ckanext.yukon.login.safe_ip = 127.0.0.1 *.*.*.*

###############################################################################
#                          Environment settings: end                          #
###############################################################################

licenses_group_url = file://%(here)s/licenses-yukon.json

## plugins
ckan.plugins =
             yukon
             downloadall
             activity
             scheming_datasets
             envvars
             saml
             ingest
             harvest ckan_harvester
             theming

ckan.ui.theme = yukon
ckan.ui.enable_theming_views = true

ckan.views.default_views =
                         image_view text_view  datatables_view webpage_view

ckan.preview.image_formats = png jpeg jpg gif svg

ckan.locale_default = en
ckan.locales_offered = en fr

ckan.uploads_enabled = true

ckan.files.storage.default.type = ckan:fs
ckan.files.storage.default.path = %(ckan.storage_path)s
ckan.files.storage.default.initialize = true

## ckanext-scheming
scheming.dataset_schemas =
                         ckanext.yukon:schemas/data_schema.yaml
                         ckanext.yukon:schemas/information_schema.yaml
                         ckanext.yukon:schemas/access-requests_schema.yaml
                         ckanext.yukon:schemas/pia-summaries_schema.yaml
scheming.dataset_fallback = true

# scheming.group_schemas = ckanext.yukon:schemas/group.yaml
# scheming.organization_schemas = ckanext.yukon:schemas/organization.yaml

scheming.presets =
                 ckanext.yukon:schemas/presets.yaml
                 ckanext.scheming:presets.json

## ckanext-editable-config
ckanext.editable_config.replace_admin_config_tab = true

## ckanext-saml
ckan.saml_custom_base_path = %(here)s/saml
ckan.saml_use_https = true
ckanext.saml.settings.dynamic = true
ckanext.saml.session.ttl = 2_592_000
ckanext.saml.reactivate_deleted_account = true
ckanext.saml.settings.substitution.SITE_URL = %(ckan.site_url)s
ckanext.saml.settings.substitution.SP_ENTITY_ID = %(ckan.site_url)s
ckan.saml.name_from_response = true
ckan.saml.user_fields_trigger_update = fullname name
ckanext.saml.login_button_text = MyYukon Login

## ckanext-spatial
ckanext.spatial.search_backend = solr-bbox
ckanext.spatial.common_map.type = custom
ckanext.spatial.common_map.custom_url = https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/tile/{z}/{y}/{x}
ckanext.spatial.common_map.attribution = Tiles courtesy of the <a href="https://usgs.gov/">U.S. Geological Survey</a>

## ckanext-harvest
ckan.harvest.mq.type = redis

## develop
ckan.devserver.watch_patterns =
    %(here)s/ckanext-yukon/ckanext/yukon/schemas/dataset.yaml
    %(here)s/ckanext-yukon/ckanext/yukon/schemas/organization.yaml
    %(here)s/ckanext-yukon/ckanext/yukon/schemas/group.yaml
    %(here)s/ckanext-yukon/ckanext/yukon/schemas/presets.yaml
    %(here)s/ckanext-yukon/config/project.ini

# Auth settings
ckan.auth.anon_create_dataset = false
ckan.auth.create_unowned_dataset = false
ckan.auth.allow_dataset_collaborators = true
ckan.auth.allow_admin_collaborators = true
ckan.auth.public_user_details = false
ckan.auth.user_create_organizations = false
ckan.auth.user_create_groups = false
ckan.auth.user_delete_groups = false
ckan.auth.user_delete_organizations = false
beaker.session.timeout = 6_000_000
ckan.dataset.create_on_ui_requires_resources = false

# Frontend settings
ckan.site_logo = /images/logo.png
ckan.favicon = /images/favicon.ico
